@startmindmap
* 总体架构
** 业务架构
*** 教学
*** 运营
*** 销售
*** 技术
** 技术架构
*** 终端
**** 学员
***** PC
***** App
***** 小程序
***** 微站
**** 教研
***** PC
***** App
**** 教务
***** PC
***** App
**** 营销
***** PC
**** 财务
***** PC
*** 前端服务
**** 资讯
***** SEO
**** 产品
***** SEO
***** 公开课
***** 正课
****** 互动(一对N)
****** 习题-题库
****** 答疑
****** ...
**** 购课
***** 购物车
***** 市场策略
****** 折扣
****** 拼团
****** 限购
****** ...
***** 订单
****** 对账
****** 退费
****** ...
***** 支付
*** 后端
**** 业务后端
***** 用户服务
****** 认证
****** 鉴权
***** 产品服务
****** 一对N
****** 直播
****** 录播
****** 题库
****** 教材
***** 订单服务
***** 市场服务
***** 学习服务
***** 销售服务
***** 内容服务
***** 业务日志
***** 数据分析
***** 机器学习
**** 技术后端
***** API网关
***** 应用日志
***** 系统预警
***** APM
***** 服务治理
****** 发现
****** 注册
****** 监控
****** 熔断降级
**** 基础设施
***** 运行时
****** Docker
****** Docker-Compose
****** Kubernetes
***** 开发语言
****** AspnetCore
****** Java
****** Python
****** Go
***** 服务通信
****** Rest
****** RPC
****** 异步消息
***** 持久化
****** 关系数据库
******* 自建
******** Mysql
******** Postgresql
******* RDS
****** NoSql
******* Redis
******* Mongodb
******* Cassendra
******* ElasticSearch
*** 实践
**** Linux
**** Git
**** CNCF
**** 敏捷
**** CI/CD
**** DevOps

@endmindmap